project:
  type: website
  output-dir: _site

website:
  title: "Zackelsey Van Lyfe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
  page-footer:
    left: "Built with Quarto"
    right: "LFG"
  repo-url: https://github.com/YOUR-USERNAME/YOUR-REPOSITORY
  repo-actions: [edit, issue]

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    link-external-newwindow: true
